<h1>NumPy Basics </h1>

<h2> Basic syntax</h2>

In [254]:
import numpy as np

This is a normal list in python. Lists can store objects of different datatype simultaneously.

In [255]:
MyList=[1,2,3,4]

In [256]:
print(type(MyList))

<class 'list'>


<h3><b>np.array()</b></h3>

A numpy array is very similar to a list. The main benefits of using NumPy arrays should be smaller memory consumption and better runtime behavior.  

In [257]:
MyArray=np.array(MyList)
print(type(MyArray))


<class 'numpy.ndarray'>


A numpy array should be homogenous.i.e all elements within it should be if the same datatype. When multiple datatypes are gicen as inputs for the array, it automatically attempts to convert it to a homogenous array

In [258]:
MyList2=[1,"hello",True]
MyArray2=np.array(MyList2)

It can be seen that despite an integer,string, and a boolean being given as the input, the final numpy array has converted everything into strings in order to maintain homogenety.

In [259]:
print(MyArray2)
print(type(MyArray2))

['1' 'hello' 'True']
<class 'numpy.ndarray'>


<h3><b>np.zeros()</b></h3>

The np.zeros method creates an array of 0s. The shape of the arrays, as swell of the dataype of the 0s (either int or  float) can be set by the user. shape=(rows,colums)  


In [260]:
zArray=np.zeros(shape=(2,2))
print(zArray)

[[0. 0.]
 [0. 0.]]


In [261]:
zArray=np.zeros(shape=(3,2),dtype=int)
print(zArray)

[[0 0]
 [0 0]
 [0 0]]


<h3><b>np.ones()</b></h3>

Similary,the np.ones method creates an array of 1s. The shape of the arrays, as swell of the dataype of the 1s (either int or  float) can be set by the user. shape=(rows,colums)  

In [262]:
oArray=np.ones((2,2))
print(oArray)

[[1. 1.]
 [1. 1.]]


In [263]:
oArray=np.ones((2,2),dtype=int)
print(oArray)

[[1 1]
 [1 1]]


<h2> Basic functions</h2>

<h3><b>np.arange()</b></h3>

The .range() function is used in python to generate a sequence of numbers.The parameters are, the starting number, the ending number (the range is not inclusive of this number), and the increment/decrement between each number in the range sequence.

In [264]:
range(1,10,1)

range(1, 10)

In [265]:
print(list(range(1,10,1)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [266]:
range(10,1,-1)

range(10, 1, -1)

In [267]:
print(list(range(10,1,-1)))

[10, 9, 8, 7, 6, 5, 4, 3, 2]


The range function cant create a reverse sequence unless you specify the decrement in the parameters.If you dont specify the decrement, it creates an empty list.

In [268]:
range(10,1)
print(list(range(10,1)))

[]


Similarly,in numpy the .arange() function is used to produce a sequence of numbers as an array 

In [269]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [270]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [271]:
np.arange(10,1)

array([], dtype=int64)

<h3><b>np.random</b></h3>

One of the more commonly used functions is to generate random numbers

We first set the seed for the random number.Random numbers are not truly random. They are a function of the seed. For a given seed the same set of random numbers will always be generated.

In [272]:
np.random.seed(101)

We now call randint to get an array of random ints. The parameters are (starting value, ending value, the number of random integers to be generated)

In [273]:
arr=np.random.randint(0,100,10)
print(arr)
print(type(arr))

[95 11 81 70 63 87 75  9 77 40]
<class 'numpy.ndarray'>


In [274]:
arr2=np.random.randint(0,100,10)
print(arr2)
print(type(arr2))

[ 4 63 40 60 92 64  5 12 93 40]
<class 'numpy.ndarray'>


<h3><b>np.max()</b></h3>

The largest element in the NumPy array can be returned using the .max() function

In [275]:
print(arr.max())
print(arr2.max())

95
93


<h3><b>np.argmax()</b></h3>

The argmax() method returns the index of the largest element in the array

In [276]:
print(arr.argmax())

0


In [277]:
print(arr2.argmax())

8


<h3><b>np.min(),np.argmin()</b></h3>

Similarly min and argmin are used to the return the smallest value and it's index.

In [278]:
print(arr.min())
print(arr.argmin())
print(arr2.min())
print(arr2.argmin())

9
7
4
0


<h3><b>.mean()</b></h3>

The .mean() function returns the mean of the array

In [279]:
arr.mean()


60.8

<h3><b>.reshape()</b></h3>

Reshaping arrays is done by the .reshape() function. If the parameters for reshaping are incompatible with the array, an error is thrown.

In [280]:
print("Before reshape:")
print(arr)
print("Shape",arr.shape,sep=':')
arr=arr.reshape((5,2))
print("After reshape:")
print(arr)
print("Shape",arr.shape,sep=':')


Before reshape:
[95 11 81 70 63 87 75  9 77 40]
Shape:(10,)
After reshape:
[[95 11]
 [81 70]
 [63 87]
 [75  9]
 [77 40]]
Shape:(5, 2)


You can also let python figure out the optimal shape by giving only one parameter and setting the other as -1

In [287]:
arr=arr.reshape((2,-1))
print(arr)

[[95 11 81 70 63]
 [87 75  9 77 40]]


In [289]:
arr=arr.reshape((10,-1))
print(arr)

[[95]
 [11]
 [81]
 [70]
 [63]
 [87]
 [75]
 [ 9]
 [77]
 [40]]


In [290]:
arr=arr.reshape(-1,10)
print(arr)

[[95 11 81 70 63 87 75  9 77 40]]


<h2>Accesing elements of array</h22>

In [281]:
mat=np.arange(0,100).reshape((10,10))
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


The elements of the array can be accessed using arr[row,column] or arr[row][column]

In [282]:
row=3
column=4
print(mat[row,column])
print(mat[row][column])

34
34


The matrix can be sliced to obtain specific rows or columns. This is done by mat[:,column] or mat[row,:]

In [284]:
print(mat[:,column])
print(mat[row,:])

[ 4 14 24 34 44 54 64 74 84 94]
[30 31 32 33 34 35 36 37 38 39]


It is possible to slice multiple rows and columns ar the same time. This can be done as follows

In [291]:
SubArray=mat[0:row,0:column]

In [292]:
print(SubArray)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]


The methods in numpy can be called in a nested fashion. For example instead of

In [285]:
var=mat[:,column]
var=var.reshape((5,2))
print(var)

[[ 4 14]
 [24 34]
 [44 54]
 [64 74]
 [84 94]]


In [286]:
print(mat[:,column].reshape((5,2)))

[[ 4 14]
 [24 34]
 [44 54]
 [64 74]
 [84 94]]


<h3><b>.copy()

the .copy() function creates a deep copy (i.e both variables have same values but different memory location). Changes made in the copied array will not be reflected in the original and vice versa

In [293]:
newmat=mat.copy()
print(newmat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [294]:
newmat[row][column]=9999


In [295]:
print(newmat)

[[   0    1    2    3    4    5    6    7    8    9]
 [  10   11   12   13   14   15   16   17   18   19]
 [  20   21   22   23   24   25   26   27   28   29]
 [  30   31   32   33 9999   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49]
 [  50   51   52   53   54   55   56   57   58   59]
 [  60   61   62   63   64   65   66   67   68   69]
 [  70   71   72   73   74   75   76   77   78   79]
 [  80   81   82   83   84   85   86   87   88   89]
 [  90   91   92   93   94   95   96   97   98   99]]


In [296]:
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
